# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cultura Visual y Sonora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for Cultura Visual y Sonora
pod 'BoringSSL-GRPC'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'BoringSSL-GRPC', '= 0.0.3', :modular_headers => false
pod 'gRPC-Core', '= 1.21.0', :modular_headers => false
end
